dist: xenial
language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/go-redis/redis

script:
 - go test ./supervisor -v